/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cloud_logic_custom": [
        {
            "name": "AdminQueries",
            "endpoint": "https://ky1zqchp93.execute-api.us-east-1.amazonaws.com/pantryap",
            "region": "us-east-1"
        }
    ],
    "aws_appsync_graphqlEndpoint": "https://paiw3imfpbhhdob2xtd2xiztie.appsync-api.us-east-1.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-1",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-rhrg6fbijncw7gjs2rycune4hu",
    "aws_cognito_identity_pool_id": "us-east-1:8fd1532d-0150-4dbe-a98a-473700d0540a",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_IdQPVnM3f",
    "aws_user_pools_web_client_id": "5k8i79mu3qiadnu6fjlhn0uvd7",
    "oauth": {},
    "aws_cognito_username_attributes": [
        "EMAIL"
    ],
    "aws_cognito_social_providers": [],
    "aws_cognito_signup_attributes": [
        "EMAIL"
    ],
    "aws_cognito_mfa_configuration": "OFF",
    "aws_cognito_mfa_types": [
        "SMS"
    ],
    "aws_cognito_password_protection_settings": {
        "passwordPolicyMinLength": 8,
        "passwordPolicyCharacters": []
    },
    "aws_cognito_verification_mechanisms": [
        "EMAIL"
    ],
    "aws_content_delivery_bucket": "antryapp3-20250612095949-hostingbucket-pantryap",
    "aws_content_delivery_bucket_region": "us-east-1",
    "aws_content_delivery_url": "https://d2luq3gr1iysc5.cloudfront.net",
    "aws_user_files_s3_bucket": "pantryapp3d9953cb857974877951af58fc155038036060-pantryap",
    "aws_user_files_s3_bucket_region": "us-east-1"
};


export default awsmobile;
